package com.flowwallet.common.dto;

import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.math.BigDecimal;

/**
 * Inter-service request from Wallet Service to Payment Service (via OpenFeign)
 * to create a payment transaction.
 *
 * @param transactionReference unique reference generated by Wallet Service (idempotency key)
 * @param amount               top-up amount in major currency units (e.g. 50.00)
 * @param currency             ISO 4217 currency code
 * @param walletId             target wallet ID
 * @param providerName         payment provider (e.g. STRIPE)
 */
public record CreatePaymentIntentRequest(
        @NotBlank(message = "Transaction reference is required")
        @Size(max = 64, message = "Transaction reference must not exceed 64 characters")
        String transactionReference,
        
        @NotNull(message = "Amount is required")
        @DecimalMin(value = "1.00", message = "Minimum top-up amount is 1.00")
        @DecimalMax(value = "10000.00", message = "Maximum top-up amount is 10,000.00")
        BigDecimal amount,
        
        @NotBlank(message = "Currency is required")
        @Size(min = 3, max = 3, message = "Currency must be exactly 3 characters")
        String currency,
        
        @NotNull(message = "Wallet ID is required")
        Long walletId,
        
        @NotBlank(message = "Provider name is required")
        @Size(max = 32, message = "Provider name must not exceed 32 characters")
        String providerName
) {
}
