package com.flowwallet.common.dto;

import java.math.BigDecimal;

/**
 * Inter-service request from Wallet Service to Payment Service (via OpenFeign)
 * to create a Stripe PaymentIntent.
 *
 * @param transactionReference unique reference generated by Wallet Service (idempotency key)
 * @param amount               top-up amount in major currency units (e.g. 50.00 PLN)
 * @param currency             ISO 4217 currency code
 * @param walletId             target wallet ID
 * @param userId               wallet owner's user ID
 */
public record CreatePaymentIntentRequest(
        String transactionReference,
        BigDecimal amount,
        String currency,
        Long walletId,
        String userId
) {
}
